### ISSUE TITLE
添加Dockerfile的构建和github action

### ISSUE THREAD

**Issue by incubator4** [vapehacker/bili-auth#10]
如题，希望可以有Dockerfile，并且通过github action push到 docker hub，如果可以的话，我可以提供PR来添加这个功能

**Comment by icyux** [comment]
你好，用 Docker 来部署这个应用听上去很不错。不过我的确不怎么了解 Docker 和 Github Action，如果你能提供 PR 的话我将感激不尽。另外，若是用 Dockerfile 构建需要对项目结构作一些调整之类的，也请你告诉我。

**Comment by icyux** [comment]
感谢你的提议，已添加 Dockerfile 并将构建完的镜像上传到 Docker Hub。至于使用 GitHub Action 自动构建的话，由于项目目前没有频繁的更新，也许以后再考虑了。此外，我还是对 Docker 这块不太了解，如果你有空测试下这个镜像的话也欢迎反馈问题。
