### ISSUE TITLE
接入直播间弹幕库代替私信获取

### ISSUE THREAD

**Issue by icyux** [vapehacker/bili-auth#7]
能否尝试接入直播间弹幕[库](https://github.com/xfgryujk/blivedm)代替私信获取，需要发送随机字符串以鉴权

_Originally posted by @7est in https://github.com/vapehacker/bili-auth/issues/6#issuecomment-1328240229_

**Comment by icyux** [comment]
@7est
为了方便讨论，单独开了一个 issue。接入直播间弹幕库的话，是个好想法，技术实现上也没有问题。因此不妨往下讨论一下吧。

直播间弹幕的话，我不清楚未实名认证的用户能否开通一个至少能够发送弹幕的直播间。如果方便的话，你能考证一下这点吗？因为发送私信基本没有门槛，只需要手机号验证就可以了。为了确保项目的通用性，即使接入直播间弹幕的话也是并列的选项，“代替”发送私信的方式目前没有考虑。

另外，考虑到直播间弹幕对任何人公开，尽管随机字符串（Verify ID）泄露没有安全问题，这点在设计时已经考虑到，但是任何人都可以得知你正在进行验证。相比于私信来说，这种方式的隐私性就略逊一筹了。

以上是目前我的考量，如果你有特殊的应用场景不妨提出我们讨论一下。

**Comment by LaT-Tee** [comment]
验证未实名认证的用户直播间：正巧我自己就有一个没有实名认证过的账号，实测无法打开直播间，会直接显示“非常抱歉该页面暂时无法访问”
关于想法：我认为这样子可以不频繁循环延时请求数据，且开发门槛比较低，而且我认为这对主要活动在直播间的B站主播来说是一个很好的验证方式。
关于可能遇到的问题：B站直播间弹幕的屏蔽词很多，需要增加判断，如特定数字组合。

**Comment by icyux** [comment]
@7est 
首先辛苦你考证了这个问题，这样的话这个功能的需求群体明确为已经实名认证的主播了。我还是对应用场景有些疑问：在直播间弹幕中发送，是否对正常互动氛围有些干扰呢？另外相比于私信发送，暂且抛开下面谈到的技术方面优势，这种方式是否有额外优势呢？

另外，循环请求的问题。你提到的获取直播间弹幕的库使用的是 WebSocket 获取，相比现在使用的轮询（间隔五秒）的方式获取有优势，不过后者目前似乎不是性能瓶颈，尽管我没有实验过。

屏蔽词，这个确实，发送私信也需要考虑，否则容易被风控。后续会加上预检测屏蔽词。

**Comment by LaT-Tee** [comment]
很抱歉，我觉得这个思路仅仅是对于目前无法用私信这个情况所做的替代方案，没有什么实际的额外优势。
甚至私信没有字数限制，而直播弹幕有字数限制。

对于影响弹幕氛围这件事情，我认为也可以用小号来代替。不过我觉得也不一定是主播可以采用这种方式，任何实名认证通过的用户都可以用这种方式，不管用不用直播间。

**Comment by LaT-Tee** [comment]
另外我突然想到了一种情况，虽然说不痛不痒，但是可以考虑和扩展：通过直播弹幕来鉴权的话可以获取用户是否上舰的信息，也就是说假设应用场景里有需要给用户分不同奖励的情况的话就可以适用。比方说在评论区里，舰队的用户可以有尊贵头像框之类的。

**Comment by icyux** [comment]
@7est 
总之多谢提供这个想法，之前确实没有考虑过以直播间弹幕的方式来实现。虽然说任何实名用户都可使用，或者说用小号解决互动氛围的问题，但直播间弹幕的公开性使得它在鉴权这个应用场景略逊一筹。综合上面的讨论，我认为目前还是私信更加合适，如果以后有更合适的机会再考虑用直播间弹幕作为备选方案。

另外你提到获取用户上舰信息的场景。主播大航海的列表是公开的，且可以获取到所有上舰用户的 UID。因此通过私信同样可以实现这个功能，只需要在鉴权后获取到用户的 UID，然后查询是否在列表中即可。不过我觉得这个项目主要是用于鉴权，只需获取到用户的基本信息即可，其他的可以自行扩展，不必一并集成在项目中。

感谢对本项目的关注与贡献！针对这个问题，我们可以继续讨论；如果有新的想法，也欢迎提出。
