### ISSUE TITLE
关于该项目的一些想法

### ISSUE THREAD

**Issue by yllhwa** [vapehacker/bili-auth#8]
一年前由于要开展年报活动，需要b站的鉴权，参考您的思路编写了一个oauth的[实现](https://github.com/ASoulCnki/oauth)和前端[实现](https://github.com/ASoulCnki/AsoulCnkiOAuthFrontend).
今天偶然再次翻阅到这个项目，想谈一谈实践中出现的问题和解决方案。
1. 移动端（Android和IOS）用户占比不可忽视，而在移动端链接跳转Web对话页面（`https://message.bilibili.com/#/whisper/mid${botUid}`）的体验是不佳的。第一，用户可能没有在浏览器登录B站；其次，B站在移动端没有对该界面进行适配，操作体验不佳。我们的改进方案是，前端通过UA判断客户端类型，在移动端采用URL Scheme跳转打开该用户的主页（即`bilibili://space/${botUid}`），实际体验效果良好。
2. 对于在网站中因为防盗链无法引用B站头像的问题，事实上B站的防盗链只是校验了referer，甚至允许空referer，只需要为图像添加`noreferrer`属性即可。
3. 在我们完成年报活动后，B站似乎对私信进行了一些限制，未互关的用户每日发送消息条数存在限制。但是我最近测试发现，只要关注后就可以发送多条消息，通过私信鉴权还是存在实用性的。

我们在去年的年报活动中，oauth服务经过了1w次以上的调用，工作良好。事实证明普通用户也能够理解并使用这种第三方的鉴权项目。

**Comment by icyux** [comment]
你好，很高兴你能关注到这个项目。关于你的想法，我的思考如下。

1. 使用 URL Scheme 跳转。好建议，这样确实会方便很多，后续会加上这个。另外我也有进一步的想法，对于用户在移动端登录B站、桌面端鉴权的场景，可以将 URL Scheme 编码为二维码，用户可以直接扫码跳转到个人主页。我不清楚 URL Scheme 中能否携带更多信息，如果能直接带上私信内容就更加方便了。
2. 头像防盗链。这是我的疏忽，一开始测试时我弄错了，以为头像防盗链必须携带有效的 `Referer` 头，因此额外在服务端添加了代理获取头像的功能。后续会把这个功能去掉。
3. 私信发送频率限制。是的，我也注意到这个问题，未关注时似乎只能发送 1~2 条消息。不过对于鉴权请求来说，一条消息就足够；而且 bot 回复之后，后续消息好像就没有限制了，这一点我没有详细测试。

感谢分享想法！期待后续交流。

**Comment by yllhwa** [comment]
> 私信发送频率限制。是的，我也注意到这个问题，未关注时似乎只能发送 1~2 条消息。不过对于鉴权请求来说，一条消息就足够；而且 bot 回复之后，后续消息好像就没有限制了，这一点我没有详细测试。

谈到私信限制，让机器人给用户发消息不太好，在大量使用的情况下可能会触发B站的风控，其实直接让用户发送后再在网站上点击确认就可以了呀。

**Comment by icyux** [comment]
> 谈到私信限制，让机器人给用户发消息不太好，在大量使用的情况下可能会触发B站的风控，其实直接让用户发送后再在网站上点击确认就可以了呀。

关于风控我是这样想的。私信骚扰这类行为的特征一般是频繁地主动发起对话。而在鉴权流程中，主动发起对话的是用户一方，bot 仅在收到用户命令后才会做出回复，这点和一般用户的行为还是接近的（比如说UP主回复大量来自关注者的消息）；另外我也设置了发送频率限制的功能。这样的话被判定为滥用行为的可能性还是比较小的。

至于为什么 bot 要回复一条消息，由于用户仅需发送一条形如 `/auth 1234abcd` 的消息即可完成验证，没有后续确认操作，因此这样的操作有一定风险。这条消息其实是意义不明的，大部分用户并不了解"auth"是什么的缩写，也不知道发送一条私信会有什么后果。因此我可以有很多理由来诱骗目标用户向机器人发送这条消息，以其身份完成鉴权，而目标用户对发生了什么一无所知。所以我加入了带有明确说明的验证响应，应该足以让用户认识到误发送的后果，有必要时用户可执行撤销操作。

关于这点我们可以进一步讨论一下。说实话我对目前这个亡羊补牢式的操作不是很满意，因为自用户收到验证响应起本次鉴权就已经成功了，手速快一点完全可以在目标用户做出反应执行撤销操作之前完成应用授权，这时候再撤销已经晚了。后续我会改进交互的逻辑，比如说增加后续确认或者在待发送消息中添加更明确的声明。

**Comment by yllhwa** [comment]
> 这点和一般用户的行为还是接近的（比如说UP主回复大量来自关注者的消息）

实际上B站的风控还会对条数进行限制，据目前掌握的消息来看，每天能发送的消息不会多于1k条。当然，小体量的情况下可以不考虑，大体量情况下如果还要回复的话可以考虑我们使用的多个bot账号进行负载均衡。

对于防止用户被诱导授权的情况，目前的发送后提醒功能可以通过B站的`关注回复消息`、`关键词回复消息`实现，比如检测到关键词auth就返回提示词，这个应该不会触发风控。

>说实话我对目前这个亡羊补牢式的操作不是很满意，因为自用户收到验证响应起本次鉴权就已经成功了，手速快一点完全可以在目标用户做出反应执行撤销操作之前完成应用授权，这时候再撤销已经晚了。后续我会改进交互的逻辑，比如说增加后续确认或者在待发送消息中添加更明确的声明。

比这还好的方法我暂时想不出来，在用户发送的消息中携带提示信息这个方法确实不错。比如`/auth 1234abcd 请勿泄露此token`，然后强制校验用户发送的消息带有这条提示信息。

**Comment by icyux** [comment]
> 实际上B站的风控还会对条数进行限制，据目前掌握的消息来看，每天能发送的消息不会多于1k条。当然，小体量的情况下可以不考虑，大体量情况下如果还要回复的话可以考虑我们使用的多个bot账号进行负载均衡。

好的，关于消息限制的我明白了，以后还是提供一个可以禁用 bot 回复的配置选项。另外配置多个 bot 帐号在大规模应用时确实是有必要的，后续考虑加入。

> 对于防止用户被诱导授权的情况，目前的发送后提醒功能可以通过B站的`关注回复消息`、`关键词回复消息`实现，比如检测到关键词auth就返回提示词，这个应该不会触发风控。

我查了一下，开启自动回复的要求似乎有点苛刻，需要1k粉丝，bot 帐号一般达不到这个要求吧...

> 比这还好的方法我暂时想不出来，在用户发送的消息中携带提示信息这个方法确实不错。比如`/auth 1234abcd 请勿泄露此token`，然后强制校验用户发送的消息带有这条提示信息。

我也更偏向这个方案。唯一问题是在登录B站帐号与鉴权不在同一个设备上的场景，这时用户需要手动输入私信，更长的消息会影响用户体验。不过考虑到提示消息不会过于冗长，问题没有那么突出。
