### ISSUE TITLE
可以支持更多的数据库后端吗

### ISSUE THREAD

**Issue by incubator4** [vapehacker/bili-auth#9]
注意到当前项目使用sqlite3作为数据库，并且在main.py中写死了
实际上我希望数据库的连接希望可以在config.toml中定义

**Comment by icyux** [comment]
你好，目前关于数据库的实现确实比较简陋，不过我会尽快提供可自行配置的 MariaDB / MySQL 支持。

**Comment by icyux** [comment]
在 a77ac0d 中已经提供了对 MariaDB / MySQL 数据库的支持。在 4c3c4d7 提供了相关文档。

**Comment by incubator4** [comment]
> 在 [a77ac0d](https://github.com/vapehacker/bili-auth/commit/a77ac0d37e0a2c28ab04420780511dfcc0967ef1) 中已经提供了对 MariaDB / MySQL 数据库的支持。在 [4c3c4d7](https://github.com/vapehacker/bili-auth/commit/4c3c4d7e94020c61fe818331711acaba6881e0af) 提供了相关文档。

我想问一下，是出于哪方面的考虑，才没有使用例如 SQLAlchemy 之类的 ORM 框架，以便更好的支持多种类型的数据库。 如果可以的话，我可以提供相关PR支持

**Comment by icyux** [comment]
主要是考虑到尽量少的修改。PyMySQL 的接口和之前类似，因此之前适用 SQLite3 的代码基本无需改动... 不过我不介意使用 ORM 框架，并且后续数据库操作的这部分也是会重构的。如果你能为此项目提供 PR 我也感激不尽。
